reporting:
  reports:
    - html
    - clover
check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
    excludes: []
  each:
    statements: 85
    lines: 85
    branches: 80
    functions: 85
