language: node_js

node_js:
  - "6"

script:
  - npm run lint
  - npm test

addons:
  code_climate:
    repo_token:
      secure: "0b080b14c35fb1bbbcc2978a8edf97cbae3d3341078e273f9ba1f6c3928c5ae2"

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
